# Generated by Django 2.0.7 on 2018-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_logo',
            field=models.CharField(default='http://www.gnc.com/dw/image/v2/BBLB_PRD/on/demandware.static/-/Sites-master-catalog-gnc/default/dwda07b782/hi-res/527156_1.jpg?sw=2000&sh=2000&sm=fit', max_length=500),
            preserve_default=False,
        ),
    ]
