# Generated by Django 2.0.7 on 2018-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_store_product_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_logo', models.CharField(max_length=500)),
                ('breakfast_detail', models.CharField(max_length=1200)),
                ('lunch_logo', models.CharField(max_length=500)),
                ('lunch_detail', models.CharField(max_length=1200)),
                ('dinner_logo', models.CharField(max_length=500)),
                ('dinner_detail', models.CharField(max_length=1200)),
            ],
        ),
    ]
